# Generated by Django 4.1.7 on 2023-04-01 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Plan_Kinesiologia_Fisioterapia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=40)),
                ('numero', models.IntegerField()),
                ('descripcion', models.TextField()),
                ('especialista', models.CharField(max_length=40)),
                ('paciente', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='Plan_Medicina_Deportiva',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=40)),
                ('numero', models.IntegerField()),
                ('descripcion', models.TextField()),
                ('especialista', models.CharField(max_length=40)),
                ('paciente', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='Plan_Nutricion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=40)),
                ('numero', models.IntegerField()),
                ('descripcion', models.TextField()),
                ('especialista', models.CharField(max_length=40)),
                ('paciente', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='Plan_Preparacion_Fisica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=40)),
                ('numero', models.IntegerField()),
                ('descripcion', models.TextField()),
                ('especialista', models.CharField(max_length=40)),
                ('paciente', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='Plan_Psicologia_Deportiva',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=40)),
                ('numero', models.IntegerField()),
                ('descripcion', models.TextField()),
                ('especialista', models.CharField(max_length=40)),
                ('paciente', models.CharField(max_length=40)),
            ],
        ),
    ]
