# Generated by Django 4.1.7 on 2023-04-06 23:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('AppCoder', '0004_comentario'),
    ]

    operations = [
        migrations.CreateModel(
            name='ComentarioMedicina',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=40)),
                ('mensaje', models.TextField(blank=True, null=True)),
                ('fechaComentario', models.DateTimeField(auto_now_add=True)),
                ('comentario', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comentariosMedicina', to='AppCoder.plan_medicina_deportiva')),
            ],
            options={
                'ordering': ['-fechaComentario'],
            },
        ),
        migrations.DeleteModel(
            name='Comentario',
        ),
    ]
