# Generated by Django 4.1.7 on 2023-04-06 23:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('AppCoder', '0006_comentariopsicologia_comentariopreparacionfisica_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comentariokinesiologia',
            name='comentario',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comentariosKinesiologia', to='AppCoder.plan_kinesiologia_fisioterapia'),
        ),
        migrations.AlterField(
            model_name='comentarionutricion',
            name='comentario',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comentariosNutricion', to='AppCoder.plan_nutricion'),
        ),
        migrations.AlterField(
            model_name='comentariopreparacionfisica',
            name='comentario',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comentariosPreparacionFisca', to='AppCoder.plan_preparacion_fisica'),
        ),
        migrations.AlterField(
            model_name='comentariopsicologia',
            name='comentario',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comentariosPsicologia', to='AppCoder.plan_psicologia_deportiva'),
        ),
    ]
